const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',



    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    //create user
    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAIL: 'CREATE_USER_FAIL',

    //get all users
    GET_ALL_USERS_SUCCESS: 'GET_ALL_USERS_SUCCESS',
    GET_ALL_USERS_FAIL: 'GET_ALL_USERS_FAIL',

    //delete user
    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAIL: 'DELETE_USER_FAIL',

    //edit user
    EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
    EDIT_USER_FAIL: 'EDIT_USER_FAIL',

    //get top doctor informatiom
    GET_TOP_DOCTORS_SUCCESS: 'GET_TOP_DOCTORS_SUCCESS',
    GET_TOP_DOCTORS_FAIL: 'GET_TOP_DOCTORS_FAIL',

    //get all doctor informatiom
    GET_ALL_DOCTORS_SUCCESS: 'GET_ALL_DOCTORS_SUCCESS',
    GET_ALL_DOCTORS_FAIL: 'GET_ALL_DOCTORS_FAIL',

    //get a doctor informatiom detail
    GET_A_DOCTORS_SUCCESS: 'GET_A_DOCTORS_SUCCESS',
    GET_A_DOCTORS_FAIL: 'GET_A_DOCTORS_FAIL',

    //create new infomation doctor 
    CREATE_INFO_DOCTOR_SUCCESS: 'CREATE_INFO_DOCTOR_SUCCESS',
    CREATE_INFO_DOCTOR_FAIL: 'CREATE_INFO_DOCTOR_FAIL',

    //get allcode hours
    GET_ALLCODE_HOUR_SUCCESS: 'GET_ALLCODE_HOUR_SUCCESS',
    GET_ALLCODE_HOUR_FAIL: 'GET_ALLCODE_HOUR_FAIL',

    //get allcode PROVINCE
    GET_PROVINCE_SUCCESS: 'GET_PROVINCE_SUCCESS',
    GET_PROVINCE_FAIL: 'GET_PROVINCE_FAIL',
    GET_PRICE_SUCCESS: 'GET_PRICE_SUCCESS',
    GET_PRICE_FAIL: 'GET_PRICE_FAIL',
    GET_PAYMENT_SUCCESS: 'GET_PAYMENT_SUCCESS',
    GET_PAYMENT_FAIL: 'GET_PAYMENT_FAIL',

    //get specialty
    GET_SPECIALTY_SUCCESS: 'GET_SPECIALTY_SUCCESS',
    GET_SPECIALTY_FAIL: 'GET_SPECIALTY_FAIL',

    //get clinc
    GET_CLINIC_SUCCESS: 'GET_CLINIC_SUCCESS',
    GET_CLINIC_FAIL: 'GET_CLINIC_FAIL',

})

export default actionTypes;